// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// A new error has been generated, which is not an improvement on the previous one.
/// This is a new error, which is not an improvement on the previous one.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - ''
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - ''
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCNktQV2L5nPfB5VRKLPbgsBaZ_TFp_F7M",
    appId: "1:418075503046:web:84e665b6ea349ba8d32ac7",
    messagingSenderId: "418075503046",
    projectId: "citk-connect-project",
    authDomain: "citk-connect-project.firebaseapp.com",
    storageBucket: "citk-connect-project.appspot.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCNktQV2L5nPfB5VRKLPbgsBaZ_TFp_F7M",
    appId: "1:418075503046:android:b4b353d61394a86ed32ac7",
    messagingSenderId: "418075503046",
    projectId: "citk-connect-project",
    storageBucket: "citk-connect-project.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyCNktQV2L5nPfB5VRKLPbgsBaZ_TFp_F7M",
    appId: "1:418075503046:ios:ed5b7d141e3335e2d32ac7",
    messagingSenderId: "418075503046",
    projectId: "citk-connect-project",
    storageBucket: "citk-connect-project.appspot.com",
    iosBundleId: "com.example.mobileApp",
  );

   static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyCNktQV2L5nPfB5VRKLPbgsBaZ_TFp_F7M",
    appId: "1:418075503046:ios:ed5b7d141e3335e2d32ac7",
    messagingSenderId: "418075503046",
    projectId: "citk-connect-project",
    storageBucket: "citk-connect-project.appspot.com",
    iosBundleId: "com.example.mobileApp",
  );

}
