// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNktQV2L5nPfB5VRKLPbgsBaZ_TFp_F7M',
    appId: '1:418075503046:web:84e665b6ea349ba8d32ac7',
    messagingSenderId: '418075503046',
    projectId: 'citk-connect-project',
    authDomain: 'citk-connect-project.firebaseapp.com',
    storageBucket: 'citk-connect-project.firebasestorage.app',
    measurementId: 'G-1Q57QB41WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwoIpJdF-GcUDPScrHsbcAZYwH6TfaC9Y',
    appId: '1:418075503046:android:85b43fdec24cbb11d32ac7',
    messagingSenderId: '418075503046',
    projectId: 'citk-connect-project',
    storageBucket: 'citk-connect-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJx65bF5eCPshgntMavSOjqB91uXIpFAI',
    appId: '1:418075503046:ios:e09fbea4c5a238f3d32ac7',
    messagingSenderId: '418075503046',
    projectId: 'citk-connect-project',
    storageBucket: 'citk-connect-project.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJx65bF5eCPshgntMavSOjqB91uXIpFAI',
    appId: '1:418075503046:ios:e09fbea4c5a238f3d32ac7',
    messagingSenderId: '418075503046',
    projectId: 'citk-connect-project',
    storageBucket: 'citk-connect-project.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNktQV2L5nPfB5VRKLPbgsBaZ_TFp_F7M',
    appId: '1:418075503046:web:e6dffc2b2ff0f023d32ac7',
    messagingSenderId: '418075503046',
    projectId: 'citk-connect-project',
    authDomain: 'citk-connect-project.firebaseapp.com',
    storageBucket: 'citk-connect-project.firebasestorage.app',
    measurementId: 'G-V8QPG0TSP3',
  );
}
